name: CI Test Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.7"

    - name: Set up Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest pandas sqlalchemy requests opendatasets fuzzywuzzy python-Levenshtein kaggle
    
    - name: Run tests
      run: |
        chmod +x ./project/tests.sh
        ./project/tests.sh